### ISSUE TITLE
Bug: Firebird pause process UI

### ISSUE THREAD

**Issue by KwilLuke** [kwilteam/db-admin#53]
When an instance in firebird is pausing, the UI will show the "deploying" workflow, until it is fully paused. We should change this so that it wither immediately shows paused or just does not show the deploying UI.

@Yaiba added a new API that needs to be called (for both deploy and stop). @Yaiba, can you share those APIs?

**Comment by Yaiba** [comment]
Firebird now supports admin stop/start deployment/instance, so the 'deployment page' might looks wrong if use is viewing it.
This maybe not needed for now since only admin can stop deployment/instance, so user won't expect to see the stop/start process in the 'deployment page'. 

For deployment start, `/api/sse?method=follow_deployment_start&target=XXX`;
For deployment stop, `/api/sse?method=follow_deployment_stop&target=XXX`;
